name: Build iOS VPN
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Clone Repository
        run: |
          git clone https://github.com/hiddify/hiddify-app.git .
          git checkout main

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Install Pods
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build Unsigned iOS App
        run: flutter build ios --release --no-codesign

      - name: Package into IPA
        run: |
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r my-vpn.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-vpn-app
          path: my-vpn.ipa
